# Generated by Django 3.2.9 on 2021-12-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeePepper', '0002_auto_20211205_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
